server:
  port: 8080

eureka:
  instance:
    client:
      serverUrl:
        defauleZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

    tracing:
      sampling:
        probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

  level:
    org:
      springframework:
        web: DEBUG

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/departments/**
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/api/organizations/**

  zipkin:
    baseUrl: http://localhost:9411
#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true

#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway:
#            handler:
#              RoutePredicateHandlerMapping: DEBUG
