# server:
#     port: 8082

# spring:
#     application:
#         name: employee-service

#     datasource:
#         url: jdbc:mysql://localhost:3306/employeedb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#         username: root
#         password: Pass2018

#     jpa:
#         properties:
#             hibernate:
#                 dialect: org.hibernate.dialect.MySQL8Dialect
#         hibernate:
#             ddl-auto: update

# eureka:
#     instance:
#         client:
#             serverUrl:
#                 defauleZone: http://localhost:8761/eureka

spring:
  application:
    name: employee-service

  config:
    import: optional:configserver:http://localhost:8888
